#!/usr/bin/python3

import argparse
import os


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file_path', type=str)
    args = parser.parse_args()
    input_file_path = args.input_file_path

    assert os.path.exists(input_file_path)

    EXPECTED_PREFIX = 'filesystem/'
    assert input_file_path.startswith(EXPECTED_PREFIX)
    output_file_path = input_file_path[len(EXPECTED_PREFIX):]

    cmd = ('curl -XPUT --upload-file {} http://192.168.4.1/_fs/{}'
           .format(input_file_path, output_file_path))
    print(cmd)
    os.system(cmd)
